/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#2c2c2e",
        "outline": "#8e8e93",
        "surface-container-highest": "#1c1b22",
        "surface-dim": "#050507",
        "primary-fixed": "#ffffff",
        "on-surface-variant": "#c5c5c7",
        "secondary-container": "#232228",
        "on-primary-fixed": "#000000",
        "on-primary-fixed-variant": "#2c2c2e",
        "on-tertiary-container": "#fafafa",
        "on-secondary-fixed": "#111114",
        "background": "#050507",
        "on-tertiary-fixed": "#121214",
        "secondary": "#a8a5b0",
        "inverse-on-surface": "#1e1e22",
        "on-surface-muted": "#8e8e93",
        "on-primary": "#000000",
        "secondary-fixed": "#e4e1e8",
        "on-secondary": "#1e1e22",
        "surface-container-high": "#16151c",
        "on-secondary-fixed-variant": "#2b2a30",
        "border-muted": "rgba(255, 255, 255, 0.08)",
        "glow-violet": "rgba(255, 255, 255, 0.03)",
        "inverse-primary": "#ffffff",
        "secondary-fixed-dim": "#c8c5cc",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-container-lowest": "#020203",
        "tertiary-container": "#4a4a4f",
        "on-surface": "#e4e1e8",
        "surface-variant": "#1c1c22",
        "on-error": "#690005",
        "tertiary": "#c6c6c7",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#b6b4bb",
        "surface-container-low": "#0d0c0f",
        "primary": "#ffffff",
        "glass-surface": "rgba(12, 12, 14, 0.5)",
        "primary-container": "#1c1c1f",
        "inverse-surface": "#e4e1e8",
        "surface-container": "#111114",
        "primary-fixed-dim": "#c1c1ff",
        "surface-bright": "#222228",
        "on-tertiary-fixed-variant": "#454747",
        "on-tertiary": "#2f3131",
        "error-container": "#93000a",
        "surface-tint": "#ffffff",
        "on-background": "#e4e1e8",
        "on-primary-container": "#fdf9ff",
        "error": "#ffb4ab",
        "surface": "#0c0c0e",
        "tertiary-fixed": "#e2e2e2"
      },
      borderRadius: {
        "sm": "0.125rem",
        "md": "0.25rem",
        "xl": "0.5rem",
        "2xl": "0.75rem",
        "3xl": "1rem",
      },
      spacing: {
        "base": "8px",
        "section-gap-mobile": "80px",
        "section-gap-desktop": "160px",
        "margin-mobile": "20px",
        "gutter": "32px",
        "container-max": "1200px"
      },
      fontFamily: {
        "headline-lg": ["Space Mono", "monospace"],
        "body-lg": ["Space Grotesk", "sans-serif"],
        "body-md": ["Space Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Space Mono", "monospace"],
        "label-md": ["Space Grotesk", "sans-serif"],
        "caption": ["Space Grotesk", "sans-serif"],
        "headline-sm": ["Space Mono", "monospace"],
        "display-lg": ["Space Mono", "monospace"],
        "headline-md": ["Space Mono", "monospace"],
        "serif": ["Space Mono", "monospace"],
        "grotesque": ["Space Grotesk", "sans-serif"],
        "sans": ["Space Grotesk", "sans-serif"],
        "body": ["Space Grotesk", "sans-serif"],
        "mono": ["Space Mono", "monospace"]
      },
      fontSize: {
        "headline-lg": ["56px", { "lineHeight": "1.05", "letterSpacing": "-0.02em", "fontWeight": "800" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "body-md": ["15px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg-mobile": ["36px", { "lineHeight": "1.1", "fontWeight": "800" }],
        "label-md": ["12px", { "lineHeight": "1.2", "letterSpacing": "0.15em", "fontWeight": "600" }],
        "caption": ["11px", { "lineHeight": "1.2", "fontWeight": "500" }],
        "headline-sm": ["24px", { "lineHeight": "1.3", "fontWeight": "700" }],
        "display-lg": ["96px", { "lineHeight": "0.95", "letterSpacing": "-0.04em", "fontWeight": "800" }],
        "headline-md": ["36px", { "lineHeight": "1.2", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
