/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "outline-variant": "#464556",
        "outline": "#908fa1",
        "surface-container-highest": "#34343a",
        "surface-dim": "#131318",
        "primary-fixed": "#e1dfff",
        "on-surface-variant": "#c7c4d8",
        "secondary-container": "#47464c",
        "on-primary-fixed": "#09006b",
        "on-primary-fixed-variant": "#2b20d2",
        "on-tertiary-container": "#fafafa",
        "on-secondary-fixed": "#1b1b20",
        "background": "#131318",
        "on-tertiary-fixed": "#1a1c1c",
        "secondary": "#c8c5cc",
        "inverse-on-surface": "#303035",
        "on-surface-muted": "#c7c4d8",
        "on-primary": "#1500a8",
        "secondary-fixed": "#e4e1e8",
        "on-secondary": "#303035",
        "surface-container-high": "#2a292f",
        "on-secondary-fixed-variant": "#47464c",
        "border-muted": "rgba(144, 143, 161, 0.2)",
        "glow-violet": "rgba(193, 193, 255, 0.05)",
        "inverse-primary": "#4643e9",
        "secondary-fixed-dim": "#c8c5cc",
        "tertiary-fixed-dim": "#c6c6c7",
        "surface-container-lowest": "#0e0e12",
        "tertiary-container": "#727373",
        "on-surface": "#e4e1e8",
        "surface-variant": "#34343a",
        "on-error": "#690005",
        "tertiary": "#c6c6c7",
        "on-error-container": "#ffdad6",
        "on-secondary-container": "#b6b4bb",
        "surface-container-low": "#1b1b20",
        "primary": "#c1c1ff",
        "glass-surface": "rgba(31, 31, 36, 0.4)",
        "primary-container": "#5d5cff",
        "inverse-surface": "#e4e1e8",
        "surface-container": "#1f1f24",
        "primary-fixed-dim": "#c1c1ff",
        "surface-bright": "#39393e",
        "on-tertiary-fixed-variant": "#454747",
        "on-tertiary": "#2f3131",
        "error-container": "#93000a",
        "surface-tint": "#c1c1ff",
        "on-background": "#e4e1e8",
        "on-primary-container": "#fdf9ff",
        "error": "#ffb4ab",
        "surface": "#131318",
        "tertiary-fixed": "#e2e2e2"
      },
      borderRadius: {
        "sm": "0.125rem",
        "md": "0.375rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
      },
      spacing: {
        "base": "8px",
        "section-gap-mobile": "80px",
        "section-gap-desktop": "160px",
        "margin-mobile": "20px",
        "gutter": "32px",
        "container-max": "1200px"
      },
      fontFamily: {
        "headline-lg": ["Playfair Display", "serif"],
        "body-lg": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "label-md": ["Hanken Grotesk", "sans-serif"],
        "caption": ["Hanken Grotesk", "sans-serif"],
        "headline-sm": ["Playfair Display", "serif"],
        "display-lg": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "serif": ["Playfair Display", "serif"],
        "grotesque": ["Hanken Grotesk", "sans-serif"],
        "sans": ["Hanken Grotesk", "sans-serif"],
        "body": ["Inter", "sans-serif"]
      },
      fontSize: {
        "headline-lg": ["56px", { "lineHeight": "1.1", "letterSpacing": "-0.01em", "fontWeight": "700" }],
        "body-lg": ["20px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "body-md": ["17px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-lg-mobile": ["42px", { "lineHeight": "1.1", "fontWeight": "700" }],
        "label-md": ["13px", { "lineHeight": "1.2", "letterSpacing": "0.1em", "fontWeight": "600" }],
        "caption": ["11px", { "lineHeight": "1.2", "fontWeight": "500" }],
        "headline-sm": ["28px", { "lineHeight": "1.3", "fontWeight": "600" }],
        "display-lg": ["84px", { "lineHeight": "1.0", "letterSpacing": "-0.03em", "fontWeight": "900" }],
        "headline-md": ["38px", { "lineHeight": "1.2", "fontWeight": "700" }]
      }
    },
  },
  plugins: [],
}
